-- MySQL Script generated by MySQL Workbench
-- Sun Feb 17 18:42:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Quiz` DEFAULT CHARACTER SET utf8 ;
USE `Quiz` ;

-- -----------------------------------------------------
-- Table `Quiz`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz`.`task` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Quiz`.`scores` (
  `id` INT NOT NULL,
  `score` INT NOT NULL,
  `task_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_scores_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_scores_task_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `FK_scores_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `Quiz`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,