-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 08:20:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema afp2019a
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema afp2019a
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `afp2019a` DEFAULT CHARACTER SET utf8 ;
USE `afp2019a` ;

-- -----------------------------------------------------
-- Table `afp2019a`.`question_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`question_type` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`test` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`question` (
  `id` INT(11) NOT NULL,
  `question` VARCHAR(250) NOT NULL,
  `test` INT(11) NOT NULL,
  `type` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_question_test_idx` (`test` ASC),
  INDEX `FK_question_question_type_idx` (`type` ASC),
  CONSTRAINT `FK_question_question_type`
    FOREIGN KEY (`type`)
    REFERENCES `afp2019a`.`question_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_question_test`
    FOREIGN KEY (`test`)
    REFERENCES `afp2019a`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`answer` (
  `id` INT(11) NOT NULL,
  `text` VARCHAR(250) NOT NULL,
  `correct` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `pair_id` INT(11) NULL DEFAULT NULL,
  `question` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_answer_question_idx` (`question` ASC),
  CONSTRAINT `FK_answer_question`
    FOREIGN KEY (`question`)
    REFERENCES `afp2019a`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`permission` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`role` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`role_permission` (
  `role_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `FK_role_permission_permission_idx` (`permission_id` ASC),
  CONSTRAINT `FK_role_permission_permission`
    FOREIGN KEY (`permission_id`)
    REFERENCES `afp2019a`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_role_permission_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `afp2019a`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`user` (
  `id` INT(11) NOT NULL,
  `username` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `token` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`score` (
  `id` INT(11) NOT NULL,
  `score` INT(10) UNSIGNED NOT NULL,
  `test_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_score_user_idx` (`user_id` ASC),
  INDEX `FK_score_test_idx` (`test_id` ASC),
  CONSTRAINT `FK_score_test`
    FOREIGN KEY (`test_id`)
    REFERENCES `afp2019a`.`test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_score_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `afp2019a`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afp2019a`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afp2019a`.`user_role` (
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `FK_user_role_role_idx` (`role_id` ASC),
  CONSTRAINT `FK_user_role_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `afp2019a`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `afp2019a`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
